import type { ProductDto } from "@/types/product";
import type { CategoryDto } from "@/types/category";

/** Fallback data when backend is offline — keeps UI populated for frontend dev. */
export const DEMO_CATEGORIES: CategoryDto[] = [
  { Id: 1, Name: "Electronics", IsActive: true },
  { Id: 2, Name: "Fashion", IsActive: true },
  { Id: 3, Name: "Home & Living", IsActive: true },
  { Id: 4, Name: "Sports", IsActive: true },
  { Id: 5, Name: "Beauty", IsActive: true },
  { Id: 6, Name: "Books", IsActive: true },
];

export const DEMO_PRODUCTS: ProductDto[] = [
  {
    Id: 101,
    Name: "Wireless Bluetooth Headphones",
    Description: "Premium noise-cancelling headphones with 30hr battery.",
    Price: 8999,
    Stock: 45,
    IsActive: true,
    Image: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600",
    CategoryId: 1,
    CategoryName: "Electronics",
    SellerName: "Tech Store",
    SellerId: 1,
  },
  {
    Id: 102,
    Name: "Smart Watch Pro",
    Description: "Track fitness, calls, and notifications on your wrist.",
    Price: 14999,
    Stock: 30,
    IsActive: true,
    Image: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=600",
    CategoryId: 1,
    CategoryName: "Electronics",
    SellerName: "Gadget Hub",
    SellerId: 2,
  },
  {
    Id: 103,
    Name: "Running Shoes Ultra",
    Description: "Lightweight performance shoes for daily runs.",
    Price: 5999,
    Stock: 80,
    IsActive: true,
    Image: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600",
    CategoryId: 4,
    CategoryName: "Sports",
    SellerName: "SportZone",
    SellerId: 3,
  },
  {
    Id: 104,
    Name: "Leather Crossbody Bag",
    Description: "Handcrafted genuine leather everyday bag.",
    Price: 7499,
    Stock: 25,
    IsActive: true,
    Image: "https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=600",
    CategoryId: 2,
    CategoryName: "Fashion",
    SellerName: "StyleMart",
    SellerId: 4,
  },
  {
    Id: 105,
    Name: "Organic Skincare Set",
    Description: "Complete 5-piece natural skincare routine.",
    Price: 3999,
    Stock: 60,
    IsActive: true,
    Image: "https://images.unsplash.com/photo-1556228578-0d85b1a4d571?w=600",
    CategoryId: 5,
    CategoryName: "Beauty",
    SellerName: "Glow Beauty",
    SellerId: 5,
  },
  {
    Id: 106,
    Name: "Minimal Desk Lamp",
    Description: "LED lamp with adjustable brightness and warm tones.",
    Price: 2999,
    Stock: 55,
    IsActive: true,
    Image: "https://images.unsplash.com/photo-1507473888945-8659b0199358?w=600",
    CategoryId: 3,
    CategoryName: "Home & Living",
    SellerName: "HomeCraft",
    SellerId: 6,
  },
  {
    Id: 107,
    Name: "Gaming Mechanical Keyboard",
    Description: "RGB backlit keyboard with tactile switches.",
    Price: 11999,
    Stock: 20,
    IsActive: true,
    Image: "https://images.unsplash.com/photo-1511467687856-23d96c4e0a46?w=600",
    CategoryId: 1,
    CategoryName: "Electronics",
    SellerName: "Tech Store",
    SellerId: 1,
  },
  {
    Id: 108,
    Name: "Bestseller Novel Collection",
    Description: "Set of 3 award-winning fiction titles.",
    Price: 1999,
    Stock: 100,
    IsActive: true,
    Image: "https://images.unsplash.com/photo-1512820790803-83ca734da794?w=600",
    CategoryId: 6,
    CategoryName: "Books",
    SellerName: "BookWorm",
    SellerId: 7,
  },
];
